safe: false
auto: false
server: false
host: 0.0.0.0
port: 4000
baseurl: /

source: .
destination:  ./_site
plugins:  ./_plugins
timezone: nil

future: true


name: jrbueno.com
pygments: true

permalink: date
paging_path: 'page:num'


