# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jose Bueno
email: jose@jrbueno.com
description: A passionate Full Stack Developer creating robust web applications for the modern Web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jrbueno.com" # the base hostname & protocol for your site
twitter_username: joserbueno
github_username:  jrbueno

# Build settings
markdown: kramdown
